application: u-r-not-alone-staging
version: 1
runtime: python27
api_version: 1
threadsafe: false

## Uncomment to enable App Engine appstats
# builtins:
# - appstats: on

handlers:

- url: /_checkin/.*
  script: main.py
  login: admin
  secure: always

- url: /oauth.*
  script: main.py
  secure: always

- url: /content
  static_files: reply.html
  upload: reply.html
  secure: always

- url: /settings
  static_files: settings.html
  upload: settings.html
  secure: always

- url: /.*favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  expiration: 0

- url: /img
  static_dir: img

- url: /resources
  static_dir: resources

- url: /.*
  script: main.py
  secure: always
